import 'package:flutter/material.dart';

Map<String, IconData> iconData = {
  "attach_money": Icons.attach_money,
  "monetization_on_sharp": Icons.monetization_on_sharp,
  "money_off": Icons.money_off,
  "search": Icons.search,
  "sync": Icons.sync,
  "warning": Icons.warning,
  "bar_chart_rounded": Icons.bar_chart_rounded,
  "post_add": Icons.post_add,
  "table_view_rounded": Icons.table_view_rounded,
  "view_module_rounded": Icons.view_module_rounded,
  "add_shopping_cart_rounded": Icons.add_shopping_cart_rounded,
  "person_outlined": Icons.person_outlined,
  "power_settings_new_sharp": Icons.power_settings_new_sharp,
  "reply": Icons.reply,
  "attach_money_rounded": Icons.attach_money_rounded,
  "check": Icons.check,
  "change_circle_outlined": Icons.change_circle_outlined,
  "lock": Icons.lock,
  "lock_open": Icons.lock_open,
  "paid": Icons.paid,
  "zero": Icons.exposure_zero,
  "two": Icons.looks_two,
  "filter": Icons.filter_alt,
  "portrait": Icons.portrait,
  "email": Icons.email,
  "phone_android": Icons.phone_android,
  "info": Icons.info,
  "info_outline_rounded": Icons.info_outline_rounded,
  "send": Icons.send,
  "phone_forwarded_sharp": Icons.phone_forwarded_sharp,
  "cancel": Icons.cancel,
  "mail": Icons.mail,
  "phone_iphone_rounded": Icons.phone_iphone_rounded,
  "refresh": Icons.refresh
};
